// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA9kgMlLZHNsBfFj3IoW18lM0wm_OqUzw',
    appId: '1:598025252096:web:62faa3c4776fdf083a17e5',
    messagingSenderId: '598025252096',
    projectId: 'pku-online',
    authDomain: 'pku-online.firebaseapp.com',
    storageBucket: 'pku-online.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTH-0TsiHPwwn-Mwlff1y5GKuOys5o5Vc',
    appId: '1:598025252096:android:65c98a8e154f7e683a17e5',
    messagingSenderId: '598025252096',
    projectId: 'pku-online',
    storageBucket: 'pku-online.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx6G0N6H17akkD7hsSCVLW9-DaxCGVNI4',
    appId: '1:598025252096:ios:0c02b9cea82703743a17e5',
    messagingSenderId: '598025252096',
    projectId: 'pku-online',
    storageBucket: 'pku-online.appspot.com',
    iosClientId: '598025252096-a9sa8cslcsd6e0tvbdaf8p7b9cu61i2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.uidisign05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx6G0N6H17akkD7hsSCVLW9-DaxCGVNI4',
    appId: '1:598025252096:ios:89cc8454cc624dbe3a17e5',
    messagingSenderId: '598025252096',
    projectId: 'pku-online',
    storageBucket: 'pku-online.appspot.com',
    iosClientId: '598025252096-v17ieqsfu7d35pr335rqp5cvdgl0c97p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pkuOnline',
  );
}
